

type: map
mapping:
  "archives":
    type: map
    mapping:
      "disabled": { type: bool, required: false }   # Default: False
      "base_dir": { type: str, required: false }  # Default: /data/archives_repo
      "archives":
        type: seq
        required: false
        sequence:
          - type: map
            mapping:
              "name": { type: str, required: false}    # Not used. For documentation
              "url": { type: str, required: true }
              "path": { type: str, required: true }
