# Copyright (C) 2018 BROADSoftware
#
# This file is part of EzCluster
#
# EzCluster is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EzCluster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with EzCluster.  If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.


type: map
mapping:
  "squid":
    type: map
    required: true
    mapping:
      "disabled": { type: bool, required: False }   # Default false
      "disk_space_gb": { type: number, required: False } # Default 10GB. Exclusive from cache_dir
      "cache_dir": { type: str, required: false }   # Exclusive from disk_space_gb. See http://www.squid-cache.org/Doc/config/cache_dir/
      "acls":   # http://www.squid-cache.org/Doc/config/acl/
        type: seq
        required: false
        sequence:
          - type: map
            mapping:
              name: { type: str, required: true }
              classifier: { type: str, required: true }
              value: { type: str, required: true }
      "rules": # http://www.squid-cache.org/Doc/config/htcp_access/
        type: seq
        required: false
        sequence:
          - type: map
            mapping:
              acl: { type: str, required: true }
              decision: { type: str, required: true, enum: [ "allow", "deny" ] }




              
                
