

type: map
mapping:
  "archives_repo":
    type: map
    mapping:
      "disabled": { type: bool, required: false }   # Default: False
      "base_dir": { type: str, required: false }  # Default: /data/archives_repo
      "archives":
        type: seq
        required: false
        sequence:
          - type: map
            mapping:
              "url": { type: str, required: true }
              "path": { type: str, required: true }
