# Copyright (C) 2018 BROADSoftware
#
# This file is part of EzCluster
#
# EzCluster is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EzCluster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with EzCluster.  If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.


type: map
mapping:
  "openldap_server":
    type: map
    required: true
    mapping:
      "disabled": { type: bool, required: false }
      "admin_bind_password": { type: str, required: true }
      "admin_bind_dn": { type: str, required: true }
      "query_suffix": { type: str, required: true }
      "ssl_cert_path": { type: str, required: false }   # Will be generated if not provided
      "ssl_key_path": { type: str, required: false }    # Must bee defined if ssl_cert_path is defined
      
